ALTER TABLE car ADD COLUMN body_type_id INT REFERENCES body_type(id);
ALTER TABLE car ADD COLUMN brand_id INT REFERENCES brand(id);
ALTER TABLE car ADD COLUMN gearbox_id INT REFERENCES gearbox(id);
ALTER TABLE car ADD COLUMN production_year INT;
ALTER TABLE car ADD COLUMN mileage INT;
ALTER TABLE car ADD COLUMN power INT;
ALTER TABLE car ADD COLUMN used BOOLEAN;